name: Deploy Paladins Wheelspin

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKER_USERNAME }}/paladins_wheelspin:latest
          push: true

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/paladins_wheelspin:latest
            
            # Stop and remove the old container if it exists
            docker rm -f paladins_wheelspin || true
            
            # Run the container with updated environment variables
            docker run -d --name paladins_wheelspin -p 80:6789 \
              -e VITE_BASIC_AUTH_USERNAME=${{ secrets.BA_USER }} \
              -e VITE_BASIC_AUTH_PASSWORD=${{ secrets.BA_PWD }} \
              paladins_wheelspin:latest
